### PR TITLE
Remove ssh_keys and shell from passwd.data

### PR DESCRIPTION
**Pull request by lrvick**

### CODE REVIEW

**Comment by RyanSquared** [comment]
~~Suggested patch for fixing postgrest data: https://termbin.com/xq0j~~

In addition to the postgrest changes, I've made some other changes:
- the `fingerprint` field is now exactly the same as the one given by `ssh-keygen -lf`, besides base64 padding.
  - because of this, the length of the fingerprint is now 44 instead of 64
- fixed tests

**Comment by RyanSquared** [comment]
Merged the patch myself, using hex instead of base64 for `fingerprint` field, base64 moved to `base64_fingerprint` field.

**Comment by RyanSquared** [comment]
This has been manually tested and confirmed to work. I plan to eventually rewrite the testing infrastructure using docker-compose so we don't manage Docker through Makefiles.

```
ryan@lilith ~/builds/hashbang/userdb (git)-[ssh_public_keys] 18:59:10 % curl http://localhost:3000/ssh_public_key\?base64_fingerprint=like.pGSl2PBDaMhaRiFqQiVTw5F3OWyiPg0uRMgZ2p3FfC0=             
[{"fingerprint":"a464a5d8f04368c85a46216a422553c39177396ca23e0d2e44c819da9dc57c2d","base64_fingerprint":"pGSl2PBDaMhaRiFqQiVTw5F3OWyiPg0uRMgZ2p3FfC0=","type":"ssh-ed25519","key":"AAAAC3NzaC1lZDI1NTE5AAAAIKCXEbRyTwfQLhxpt9TMlpZSSGXNwnGmFdpV+yiljd4g","comment":"Some key","uid":4000}]%
ryan@lilith ~/builds/hashbang/userdb (git)-[ssh_public_keys] 18:59:39 % curl http://localhost:3000/ssh_public_key\?fingerprint=like.a464a5d8f04368c85a46216a422553c39177396ca23e0d2e44c819da9dc57c2d
[{"fingerprint":"a464a5d8f04368c85a46216a422553c39177396ca23e0d2e44c819da9dc57c2d","base64_fingerprint":"pGSl2PBDaMhaRiFqQiVTw5F3OWyiPg0uRMgZ2p3FfC0=","type":"ssh-ed25519","key":"AAAAC3NzaC1lZDI1NTE5AAAAIKCXEbRyTwfQLhxpt9TMlpZSSGXNwnGmFdpV+yiljd4g","comment":"Some key","uid":4000}]%
ryan@lilith ~/builds/hashbang/userdb (git)-[ssh_public_keys] 18:59:46 %
```

**Comment by RyanSquared** [comment]
Dibs on writing migration scripts.

**Comment by RyanSquared** [comment]
Steps that need to be done, in order:

- [ ] This needs to be merged
- [x] The bad-user cleanup and [migration](https://gist.githubusercontent.com/RyanSquared/d76d60a8bfd47b6585781bbcf3fe8ebf/raw/fc83730ffcbddb8c85207850cfdb46def763010c/migrate.sql) will need to be run.
- [x] hashbang/gitops#39 needs to be merged, and deployed.
   - This changes the API version to v1, the first official version.
   - The API can't be changed in a backwards-incompatible way after this.
- [x] hashbang/shell-server#123 needs to be merged.
   - This changes authorized-keys to use the new v1 format.
   - This changes nss-pgsql to use the shell field instead of the shell JSON value.

**Review by drGrove — APPROVED** [review]

**Pull request merged**
