### PR TITLE
Enforce JSON schemas

### PR DESCRIPTION
**Pull request by KellerFuchs**
This uses [gavinwahl/postgres-json-schema](https://github.com/gavinwahl/postgres-json-schema) to validate JSON data against schemas in (safe) PL/pgSQL (rather than a C extension).  I gave the code a cursory review, and it is automatically tested against the standard JSON Schema testsuite.

A small Python script converts the schemas from YAML to JSON and inlines them in the constraint definition, for 2 reasons:
- the string literal is cast to `jsonb` once, when `ALTER TABLE` is executed, rather than parsing JSON over and over;
- this is simple.

~~This could use negative tests showing that the constraints are indeed enforced. (They are, currently, but an automated test is better)~~

### CODE REVIEW

**Comment by KellerFuchs** [comment]
The submodule update currently points to https://github.com/hashbang/userdb-schemas/pull/2.
We should update the PR once it gets merged.

**Comment by daurnimator** [comment]
Looks reasonable to me. I can't see any obvious issues.
Main quirk is the odd template/escaping format. But no real issues IMO.

**Comment by KellerFuchs** [comment]
@daurnimator You mean using `$$` for string literals?
That was to avoid complicated escaping, since the JSON contains both `"` and `'` .

**Comment by KellerFuchs** [comment]
I added 2 more tests (that assert we can't insert invalid JSON data) and added a defensive insert in `json-schemas.py`.
If those are OK with you, please mark the review as OK and I'll merge.

**Comment by KellerFuchs** [comment]
@daurnimator @lrvick Could you ACK this?

**Review by lrvick — APPROVED** [review]

**Pull request merged**
