### PR TITLE
Use name as ID in the hosts table

### PR DESCRIPTION
**Pull request by KellerFuchs**
There is no specific need for a numeric there, and less data is happier data.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
The spec is ambiguous: are hostnames stored as `foo` or `foo.hashbang.sh`?
I lean towards the latter, and that's what I assumed in this PR.

**Comment by daurnimator** [comment]
Would this cause any issues if we upgrade boxes?
e.g. if we wanted to upgrade ny1 to a bigger instance?

**Comment by KellerFuchs** [comment]
@daurnimator I don't really see how that changes anything in that scenario:
`name` was already `UNIQUE NOT NULL`.

**Comment by KellerFuchs** [comment]
@daurnimator Mostly, the reason I lean towards `foo.hashbang.sh` is in case we ever introduce (for whichever reason) other domain names.

I guess we can add a constraint such that (for now) all hostnames end in `.hashbang.sh`.

**Comment by daurnimator** [comment]
> I guess we can add a constraint such that (for now) all hostnames end in .hashbang.sh.

No need for a constraint I think. We can probably trust the admin adding hosts on this one :)

**Comment by KellerFuchs** [comment]
@daurnimator Mmmh, given some of the “funnier” incidents with LDAP, I'm not sure  :>
Given that the `hosts` table is small, locking the table and deleting , re-adding and re-validating the constraint is not a big issue if we ever need to add new possible domains.

**Comment by KellerFuchs** [comment]
@daurnimator @lrvick OK for merge?

**Comment by lrvick** [comment]
+1

**Pull request merged**
